apiVersion: v1
kind: Service
metadata:
  name: bio-web-service
  labels:
    app: bio-site
spec:
  type: ClusterIP
  selector:
    app: bio-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
