apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bio-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bio-web
spec:
  replicas: 1  # PVC is ReadWriteOnce, so only 1 replica
  selector:
    matchLabels:
      app: bio-site
  template:
    metadata:
      labels:
        app: bio-site
    spec:
      containers:
      - name: bio-container
        image: temitayocharles/hello-k8s:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: bio-storage
