apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bio-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bio.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bio-web-service
            port:
              number: 80
