apiVersion: apps/v1
kind: Deployment
metadata:
  name: bio-web
  labels:
    app: bio-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bio-site
  template:
    metadata:
      labels:
        app: bio-site
    spec:
      containers:
      - name: bio-container
        image: temitayocharles/hello-k8s:latest
        ports:
        - containerPort: 80
